import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync, readFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
import { createAcceptedFixtureFiles } from '../fixtures/generate.mjs';
const directory = mkdtempSync(resolve(tmpdir(), 'louty-accepted-'));
const fixtures = createAcceptedFixtureFiles(directory);
const server = createServer((req,res) => {
  const path=req.url.split('?')[0];
  if(!['/','/index.html','/version.txt','/favicon.svg'].includes(path)){res.writeHead(404).end();return;}
  res.setHeader('Content-Type',path.endsWith('.txt')?'text/plain':path.endsWith('.svg')?'image/svg+xml':'text/html');
  res.end(readFileSync(resolve(path==='/'?'index.html':path.slice(1))));
});
await new Promise(done=>server.listen(0,'127.0.0.1',done));
let browser;
try {
  browser=await chromium.launch();
  const page=await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.FORECAST_BASE_URL || `http://127.0.0.1:${server.address().port}/`);
  await page.locator('#file-input').setInputFiles([fixtures.res,fixtures.accepted,fixtures.zeroBal]);
  await page.locator('[data-f-action=manage]').waitFor();
  assert.equal(await page.locator('[data-f-filter=confirmed]').textContent(),'À facturer (estimation) · 2');
  await page.locator('[data-f-action=manage]').click();
  await page.locator('[data-f-situation=confirmed]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(),2);
  assert.equal(await page.locator('#forecast-list .forecast-row').filter({hasText:'ajout automatique'}).count(),2);
  await page.keyboard.press('Escape');
  assert.match(await page.locator('.customer-advances').innerText(),/Aucun compte d’acompte \(7040\)/);
  await page.locator('.customer-advances summary').click();
  assert.match(await page.locator('.customer-advances').innerText(),/1\s?080.*TTC/);
  const shot=async name=>{if(process.env.SMOKE_SCREENSHOT_DIR){mkdirSync(process.env.SMOKE_SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:resolve(process.env.SMOKE_SCREENSHOT_DIR,name+'.png')});}};
  await page.locator('.customer-advances').scrollIntoViewIfNeeded();await shot('advances-desktop-light');
  await page.locator('[data-f-action=manage]').click();
  const row=number=>page.locator('.forecast-row').filter({has:page.locator('p').filter({hasText:new RegExp('^'+number+' ·')})});
  assert.equal(await page.locator('.forecast-row').filter({has:page.getByRole('button',{name:'Retirer',exact:true})}).count(),3);
  await row('AUTO').getByRole('button',{name:'Retirer',exact:true}).click();
  assert.match(await row('REPEAT-1').innerText(),/Couverture complète probable du groupe/);
  await page.locator('[data-f-situation=complete]').click();
  assert.equal(await page.locator('.forecast-row').count(),2);
  await page.locator('[data-f-situation=confirmed]').click();
  assert.equal(await row('ADV').count(),0);
  await page.locator('[data-f-situation=review]').click();
  assert.match(await row('ADV').innerText(),/À vérifier/);
  assert.equal(await row('REPEAT-1').count(),0);
  await page.locator('[data-f-situation=""]').click();
  await page.locator('#forecast-year').selectOption('2024');assert.equal(await page.locator('.forecast-row').count(),1);
  await page.locator('#forecast-year').selectOption('');
  await row('ADV').getByRole('button',{name:'Ajouter',exact:true}).click();
  await page.locator('[data-advance-key]').check();
  assert.match(await page.locator('#forecast-advance-balance').innerText(),/2\s?520.*TTC/);
  assert.equal(await page.locator('#forecast-amount').inputValue(),'');
  await page.locator('#forecast-amount').fill('3000');
  assert.equal(await page.locator('#forecast-month').count(),0);await shot('advance-editor-desktop-light');
  await page.locator('#forecast-form button[type=submit]').click();
  await row('ADV-OTHER').getByRole('button',{name:'Ajouter',exact:true}).click();
  assert.equal(await page.locator('[data-advance-key]').isDisabled(),true);
  await page.keyboard.press('Escape');await page.locator('[data-f-action=close-manager]').click();
  await page.reload();await page.locator('[data-f-action=manage]').waitFor();
  await page.locator('[data-f-action=manage]').click();
  assert.match(await row('AUTO').innerText(),/Écarté manuellement/);
  await row('ADV').getByRole('button',{name:'Modifier',exact:true}).click();assert.equal(await page.locator('[data-advance-key]').isChecked(),true);
  await page.keyboard.press('Escape');await page.locator('[data-f-action=close-manager]').click();
  await page.locator('#toggle-theme').click();
  await page.locator('.customer-advances').scrollIntoViewIfNeeded();await shot('advances-desktop-dark');
  await page.setViewportSize({width:390,height:844});await page.locator('.customer-advances').scrollIntoViewIfNeeded();await shot('advances-mobile-dark');
  await page.locator('#forecast-input').setInputFiles(fixtures.unpaid);
  await page.locator('.forecast-warning [data-f-jump=review]').waitFor();await page.locator('.forecast-warning [data-f-jump=review]').click();
  await page.getByRole('button',{name:'Vérifier Client Acompte · ADV',exact:true}).click();
  assert.equal(await page.locator('[data-advance-key]').isChecked(),true);
  assert.equal(await page.locator('[data-advance-key]').isDisabled(),false);
  await page.locator('[data-advance-key]').uncheck();await shot('advance-editor-mobile-dark');
  await page.locator('#forecast-form button[type=submit]').click();
  await page.locator('#toggle-theme').click();await page.locator('.customer-advances').scrollIntoViewIfNeeded();await shot('advances-mobile-light');
  await page.locator('#file-input').setInputFiles([fixtures.res,fixtures.accepted]);
  await page.getByText('Importe la Balance pour comparer avec les comptes d’acomptes.',{exact:false}).waitFor();
  assert.match(await page.locator('.customer-advances').innerText(),/Indisponible/);
  await page.locator('[data-f-action=manage]').click();
  assert.match(await row('AUTO').innerText(),/Écarté manuellement/);
  const beforeCA = await page.locator('#cap-forecast').innerText();
  await row('Q-TTC').getByRole('button',{name:'Ajouter',exact:true}).click();
  assert.match(await page.locator('#forecast-probable-invoices').innerText(),/ID-A/);
  assert.match(await page.locator('#forecast-probable-invoices').innerText(),/ID-B/);
  assert.match(await page.locator('#forecast-probable-invoices').innerText(),/F-TTC/);
  assert.match(await page.locator('#forecast-history').innerText(),/ID différent/);
  assert.equal(await page.locator('#forecast-history tbody tr').count(),2);
  assert.match(await page.locator('#forecast-history').innerText(),/Devis examiné/);
  await page.locator('#forecast-history').scrollIntoViewIfNeeded();
  await shot('ttc-mobile-light');
  await page.setViewportSize({width:1440,height:1100}); await shot('ttc-desktop-light');
  await page.keyboard.press('Escape'); await page.locator('[data-f-action=close-manager]').click();
  await page.locator('#toggle-theme').click();
  await page.locator('[data-f-action=manage]').click();
  await row('Q-TTC').getByRole('button',{name:'Ajouter',exact:true}).click();
  await shot('ttc-desktop-dark');
  await page.setViewportSize({width:390,height:844}); await page.locator('#forecast-history').scrollIntoViewIfNeeded(); await shot('ttc-mobile-dark');
  await page.getByRole('button',{name:'Confirmer : chantier entièrement facturé',exact:true}).click();
  assert.match(await row('Q-TTC').innerText(),/Écarté manuellement/);
  await page.locator('[data-f-action=close-manager]').click();
  assert.equal(await page.locator('#cap-forecast').innerText(),beforeCA);
  await page.reload();await page.locator('[data-f-action=manage]').waitFor();
  await page.locator('#forecast-input').setInputFiles(fixtures.accepted);
  await page.locator('[data-f-action=manage]').click();
  assert.match(await row('Q-TTC').innerText(),/Écarté manuellement/);
  assert.deepEqual(errors,[]);
  console.log('Accords, exclusions persistantes, groupes répétés, acomptes TTC, zéro Balance et retrait des liens invalides validés.');
} finally {await browser?.close();await new Promise(done=>server.close(done));rmSync(directory,{recursive:true,force:true});}
