import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtempSync, readFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { chromium } from 'playwright';
import { createForecastFixtureFiles } from '../fixtures/generate.mjs';

const directory = mkdtempSync(resolve(tmpdir(), 'louty-forecast-'));
const fixtures = createForecastFixtureFiles(directory);
const server = createServer((req, res) => {
  const path = req.url.split('?')[0];
  if (!['/', '/index.html', '/version.txt', '/favicon.svg'].includes(path)) { res.writeHead(404).end(); return; }
  res.setHeader('Content-Type', path.endsWith('.txt') ? 'text/plain' : path.endsWith('.svg') ? 'image/svg+xml' : 'text/html');
  res.end(readFileSync(resolve(path === '/' ? 'index.html' : path.slice(1))));
});
await new Promise(done => server.listen(0, '127.0.0.1', done));
let browser;
try {
  browser = await chromium.launch();
  const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'no-preference' });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const base = process.env.FORECAST_BASE_URL || `http://127.0.0.1:${server.address().port}/`;
  await page.goto(base);
  await page.locator('#file-input').setInputFiles([fixtures.res, fixtures.forecast]);
  await page.locator('[data-f-action="manage"]').waitFor();
  // Exercise color transitions as well as the initial numeric animation.
  await page.evaluate(() => {
    const chart = Chart.getChart(document.querySelector('#chart-ca-mb'));
    chart.setActiveElements([{ datasetIndex: 0, index: 0 }]);
    chart.update();
  });
  await page.locator('#chart-ca-mb').hover();
  await page.waitForTimeout(1100);
  const shot = async name => {
    if (!process.env.SMOKE_SCREENSHOT_DIR) return;
    mkdirSync(process.env.SMOKE_SCREENSHOT_DIR, { recursive:true });
    await page.waitForTimeout(1600);
    await page.screenshot({ path:resolve(process.env.SMOKE_SCREENSHOT_DIR, name + '.png') });
  };
  await page.locator('[data-f-action="manage"]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 3);
  assert.equal(await page.locator('#forecast-list img').count(), 0, 'imported text must be escaped');
  const partial = () => page.locator('.forecast-row').filter({ hasText:'DEV-PARTIAL' });
  assert.match(await partial().innerText(), /par nom client/);
  await partial().getByRole('button', {name:'Ajouter', exact:true}).click();
  assert.equal(await page.locator('#forecast-amount').inputValue(), '4100');
  await page.locator('#forecast-month').fill('2025-10');
  await page.locator('#forecast-form button[type=submit]').click();
  await page.locator('[data-f-tab=selected]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 1);
  await partial().getByRole('button', {name:'Modifier', exact:true}).click();
  await page.locator('#forecast-situation').selectOption('waiting');
  await page.locator('#forecast-form button[type=submit]').click();
  await page.locator('[data-f-tab=all]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 4);
  const manual = () => page.locator('.forecast-row').filter({ hasText:'DEV-MANUAL' });
  await manual().getByRole('button', {name:'Ajouter', exact:true}).click();
  await page.locator('#forecast-amount').fill('600');
  await page.locator('#forecast-month').fill('2025-11');
  await page.locator('#forecast-form button[type=submit]').click();
  await shot('forecast-manager-desktop-light');
  await page.locator('[data-f-action=close-manager]').click();
  assert.match(await page.locator('#cap-forecast').innerText(), /600/);
  const chartForecast = await page.evaluate(() => window.Chart.getChart(document.querySelector('#chart-ca-mb')).data.datasets.find(d => d.label === 'CA confirmé à facturer HT (sélection)').data);
  assert.equal(chartForecast[10], 600); assert.equal(chartForecast[9], null, 'waiting quotes do not join confirmed forecast');
  const projectedSeries = () => page.evaluate(() => Chart.getChart(document.querySelector('#chart-cumul')).data.datasets.find(d => d.label.includes('Réalisé +'))?.data);
  const marginSeries = await projectedSeries();
  assert.ok(marginSeries[10] !== null);
  assert.equal(marginSeries[11],null,'no extension beyond last dated confirmed quote');
  await page.locator('[data-pilotage-metric=ca]').click();
  const caSeries = await projectedSeries();
  assert.equal(caSeries[10]-caSeries[6],600,'only confirmed revenue added to actual once');
  const annualRows = await page.locator('#chart-annual-progress').getAttribute('data-rows');
  assert.equal(JSON.parse(annualRows)[0].projected,caSeries[10]);
  await page.locator('[data-pilotage-metric=mb]').click();
  await page.locator('#chart-annual-progress').scrollIntoViewIfNeeded();
  await shot('outlook-desktop-light');
  await page.locator('.forecast-outlook summary').click();
  assert.match(await page.locator('.forecast-outlook').innerText(),/Coûts déjà comptabilisés/);
  await shot('outlook-calculation');
  await page.locator('.forecast-outlook summary').click();
  await page.locator('#revenue-forecast').scrollIntoViewIfNeeded();
  assert.equal(await page.locator('.forecast-dashboard-tables table').count(),2);
  await page.getByLabel('Rechercher les devis suivis').fill('DEV-PARTIAL');
  assert.match(await page.locator('section[aria-label="Devis confirmés"]').innerText(),/Aucun devis/);
  await page.getByLabel('Rechercher les devis suivis').fill('');
  assert.equal(await page.locator('.forecast-column').count(),1);
  assert.equal(await page.locator('.forecast-column').getAttribute('data-f-month'),'2025-11');
  await page.locator('.forecast-column').click();
  assert.equal(await page.locator('section[aria-label="Devis en attente"] tbody tr').count(),1);
  await page.getByRole('button',{name:'Tout afficher',exact:true}).click();
  await page.locator('section[aria-label="Devis en attente"] button').click();
  assert.equal(await page.locator('#forecast-month').isVisible(),false);
  await page.locator('#forecast-situation').selectOption('confirmed');
  assert.equal(await page.locator('#forecast-month').inputValue(),'');
  await page.locator('#forecast-month').fill('2026-01');
  await page.locator('#forecast-form button[type=submit]').click();
  assert.equal(await page.locator('.forecast-column').count(),3);
  await page.locator('section[aria-label="Devis confirmés"] button').filter({hasText:'Modifier'}).last().click();
  await page.locator('#forecast-situation').selectOption('waiting');
  await page.locator('#forecast-form button[type=submit]').click();
  assert.equal(await page.locator('.forecast-column').count(),1);
  await page.locator('#revenue-forecast').scrollIntoViewIfNeeded();
  await shot('forecast-desktop-light');
  await page.locator('#toggle-theme').click();
  await page.locator('#revenue-forecast').scrollIntoViewIfNeeded();
  await shot('forecast-desktop-dark');
  await page.locator('#chart-annual-progress').scrollIntoViewIfNeeded();
  await shot('outlook-desktop-dark');
  await page.reload();
  await page.locator('[data-f-action="manage"]').waitFor();
  assert.match(await page.locator('#revenue-forecast').innerText(), /600/);
  await page.locator('[data-f-action="manage"]').click();
  await page.locator('[data-f-tab=selected]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 2);
  await page.locator('[data-f-situation=waiting]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 1);
  assert.match(await partial().innerText(), /En attente client/);
  await page.locator('[data-f-situation=confirmed]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 1);
  assert.match(await manual().innerText(), /Chantier confirmé/);
  await page.locator('[data-f-situation=""]').click();
  await shot('forecast-manager-desktop-dark');
  await page.setViewportSize({ width:390, height:844 });
  await shot('forecast-mobile-manager-dark');
  await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth);
  await manual().getByRole('button', {name:'Modifier',exact:true}).click();
  await shot('forecast-mobile-editor-dark');
  await page.keyboard.press('Escape');
  await page.locator('[data-f-action=close-manager]').click();
  await page.locator('#revenue-forecast').scrollIntoViewIfNeeded();
  await shot('forecast-mobile-dark');
  await page.locator('#chart-annual-progress').scrollIntoViewIfNeeded();
  await shot('outlook-mobile-dark');
  await page.locator('#chart-cumul').scrollIntoViewIfNeeded();
  await shot('outlook-cumul-mobile-dark');
  await page.locator('#toggle-theme').click();
  await page.locator('#revenue-forecast').scrollIntoViewIfNeeded();
  await shot('forecast-mobile-light');
  await page.locator('#chart-annual-progress').scrollIntoViewIfNeeded();
  await shot('outlook-mobile-light');
  await page.locator('[data-f-action=manage]').click();
  await page.locator('[data-f-tab=all]').click();
  await shot('forecast-mobile-manager-light');
  await page.locator('[data-f-action=close-manager]').click();
  await page.locator('#forecast-input').setInputFiles(fixtures.changed);
  await page.waitForFunction(() => document.querySelector('#revenue-forecast').textContent.includes('1 devis sélectionné(s) à vérifier'));
  await page.locator('[data-f-action=selected]').click();
  await partial().getByRole('button', {name:'Vérifier',exact:true}).click();
  assert.equal(await page.locator('#forecast-amount').inputValue(), '4100', 'new invoice must not overwrite the manual amount');
  await page.locator('#forecast-amount').fill('3700');
  await page.locator('#forecast-form button[type=submit]').click();
  await page.locator('[data-f-action=close-manager]').click();
  // A new RES clears Pièces but preserves choices; reimport restores them.
  await page.locator('#file-input').setInputFiles(fixtures.res);
  await page.locator('[data-f-action=import]').waitFor();
  assert.match(await page.locator('#revenue-forecast').innerText(), /choix sont conservés/);
  await page.locator('#forecast-input').setInputFiles(fixtures.changed);
  await page.locator('[data-f-action=manage]').waitFor();
  await page.locator('[data-f-action=manage]').click();
  await page.locator('[data-f-tab=selected]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 2);
  await page.locator('[data-f-situation=waiting]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 1);
  assert.match(await partial().innerText(), /En attente client/);
  await page.locator('[data-f-situation=confirmed]').click();
  assert.equal(await page.locator('#forecast-list .forecast-row').count(), 1);
  assert.match(await manual().innerText(), /Chantier confirmé/);
  await page.locator('[data-f-situation=""]').click();
  assert.equal(await partial().getByRole('button', {name:'Modifier',exact:true}).count(), 1);
  await page.locator('[data-f-action=close-manager]').click();
  await page.locator('section[aria-label="Devis confirmés"] button').click();
  await page.getByRole('button',{name:'Retirer du prévisionnel',exact:true}).click();
  assert.equal(await page.locator('.forecast-column').count(),0);
  assert.equal(await projectedSeries(),undefined,'removal also clears cumulative forecast');
  assert.equal(await page.locator('.forecast-outlook').count(),0);
  assert.match(await page.locator('section[aria-label="Devis confirmés"]').innerText(),/Aucun devis/);
  assert.deepEqual(errors, []);
  console.log('Prévisionnel : import, rapprochement, ajout manuel, modification, cache, réimport, thèmes et mobile validés.');
} finally {
  await browser?.close();
  await new Promise(done => server.close(done));
  rmSync(directory, { recursive:true, force:true });
}
